# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  print_pipeline_id:
    description: "command that prints the pipelineId to the console."
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run : npm i
      - save_cache :
          key : "npm_package"
          paths :
            - /src/node_modules
      - run : npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys :
            - "npm_package"
      - run : npm i
      - run : npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys :
            - "npm_package"
      - run : npm audit

workflows:
  # Name the workflow "welcome"
  my_workflow:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - test :
          requires:
            - build
      - analyze :
          requires:
            - test